config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: 'tasks'

  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update', as: 'update_task'
  # patch 'tasks/:id', to: 'tasks#mark_complete', as: 'mark_task'

  delete 'tasks/:id', to: 'tasks#destroy', as: 'delete_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :mark_complete, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def show; end

  def edit; end

  def update
    @task.update(task_params)
    # raise
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Vanilla Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Responsive Font Size (RFS) -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/coliff/bootstrap-rfs/bootstrap-rfs.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300|Roboto:300&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/f5e55803f2.js" crossorigin="anonymous"></script>
  </head>

  <body class="bg-light">
    <div class="container my-5">
      <h1 class="my-5 text-warning">Task Manager</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <div class="form">
    <li><%= f.label :title, "Insert the title" %></li>
    <li><%= f.text_field :title %></li>
    <br>
    <li><%= f.label :details, "Insert the details" %></li>
    <li><%= f.text_field :details %></li>
    <br>
    <li><%= f.submit %><li>
  </div>
<% end %>

app/views/tasks/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= f.check_box :completed, class: 'form-check-input' %>
    <%= f.label "Mark as completed" %>
    <!-- <input type="checkbox" class="form-check-input" name="completed" value="true"> -->
    <!-- <label class="form-check-label" for="completed">Mark as completed</label> -->
  </div>

  <div class="button-container my-5">
    <%= link_to "Cancel", tasks_path, class: "btn btn-outline-secondary w-25 py-2 mr-3" %>
    <%= f.submit class: 'btn btn-primary w-25 py-2 mr-3' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'task_form', task: @task %>

app/views/tasks/index.html.erb
<div class="task-container">
  <% @tasks.each do |task| %>
    <p>
      <span>
        <% if task.completed%>
          <i class="far fa-check-square text-primary mr-2"></i>
        <% else %>
          <i class="far fa-square text-warning mr-2"></i>
        <% end %>
        </span>
      <span><%= link_to task.title.capitalize, task_path(task) %></span>
      <span>
        <%= link_to delete_task_path(task.id), method: :delete, data: { confirm: 'Do you really want to delete this task?' }, class: "text-danger ml-2" do %>
          <i class="fas fa-trash-alt mr-2"></i>
        <% end %>
      </span>
    </p>
  <% end %>
</div>

<%= link_to "Create a new task", new_task_path, class: "btn btn-outline-primary w-25 py-2 my-4 mr-3" %>

app/views/tasks/new.html.erb
<%= render 'task_form', task: @task %>

app/views/tasks/show.html.erb
<h2 class="mb-3"><%= @task.title %></h2>
<p class="task-detail mb-4"><%= @task.details %></p>

<%#= link_to mark_task_path(@task), method: :patch, class:"text-secondary" do %>
<!--   <i class="fas fa-check mr-2"></i>
  Mark as complete -->
<%# end %>

<div class="another-container pr-2 mt-3">
  <%= link_to delete_task_path(@task), method: :delete, class:"py-2 w-25 btn btn-outline-secondary" do %>
    <i class="fas fa-trash-alt mr-2"></i>
    Delete this task
  <% end %>

  <%= link_to edit_task_path(@task), class:"py-2 w-25 btn btn-outline-primary" do %>
    <i class="far fa-edit mr-2"></i>
    Edit this task
  <% end %>
</div>

<%= link_to tasks_path, class:"my-2 py-2 w-50 btn btn-primary" do %>
  <i class="far fa-eye mr-2"></i>
  Show all tasks
<% end %>